name       : xkbcomp
version    : 1.4.5
release    : 9
source     :
    - https://www.x.org/releases/individual/app/xkbcomp-1.4.5.tar.gz : e88a4d86b9925ea1e8685dd5ea29c815abafb8ddf19bf5f1a1e0650839252c23
license    : GPL-3.0-only
component  : xorg.apps
summary    : X.Org Applications - xkbcomp
description: |
    X.Org Applications - xkbcomp
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xkbfile)
    - pkgconfig(xorg-macros)
    - pkgconfig(xproto)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
