name       : xkbcomp
version    : 1.3.1
release    : 3
source     :
    - http://xorg.freedesktop.org/releases/individual/app/xkbcomp-1.3.1.tar.bz2 : 0304dc9e0d4ac10831a9ef5d5419722375ddbc3eac3ff4413094d57bc1f1923d
license    : GPL-3.0
component  : xorg.apps
summary    : X.Org Applications - xkbcomp
builddeps  :
    - pkgconfig(xkbfile)
    - pkgconfig(x11)
description: |
    X.Org Applications - xkbcomp
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
