name       : xkbcomp
version    : 1.4.0
release    : 4
source     :
    - https://xorg.freedesktop.org/archive/individual/app/xkbcomp-1.4.0.tar.gz : 7ef0cbb0c6f74b1398372b10f815027637bbd201e717eba66066188274e31fcf
license    : GPL-3.0
component  : xorg.apps
summary    : X.Org Applications - xkbcomp
builddeps  :
    - pkgconfig(xkbfile)
    - pkgconfig(x11)
description: |
    X.Org Applications - xkbcomp
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
