name       : xkbcomp
version    : 1.4.2
release    : 7
source     :
    - https://www.x.org/releases/individual/app/xkbcomp-1.4.2.tar.gz : 962a3d550ad0058c141c2bf16eed6498d0f86d987141f875cb0a5df5696487d7
license    : GPL-3.0-only
component  : xorg.apps
summary    : X.Org Applications - xkbcomp
description: |
    X.Org Applications - xkbcomp
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xkbfile)
    - pkgconfig(xorg-macros)
    - pkgconfig(xproto)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
